on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  repository_dispatch:
    types: [run-ping]

name: Create Release

jobs:
  once:
    name: Create single release for all builds
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: Create Release
    needs: once
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        arch: [amd64,arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - if: matrix.os == 'windows-latest' || matrix.arch == 'amd64'
        name: Build
        run: cmd /C "set CGO_ENABLED=0 && go build -v -o helloworld-windows-amd64-${{ github.ref_name }} ./..."  
      - if: matrix.os == 'windows-latest' || matrix.arch == 'arm64'
        name: Build
        run: cmd /C "set CGO_ENABLED=0 && go build -v -o helloworld-windows-arm64-${{ github.ref_name }} ./..."  
      - name: Test
        run: go test -v ./...
      - if: matrix.os == 'windows-latest' || matrix.arch == 'amd64'
        name: create archive windows amd64
        uses: vimtor/action-zip@v1.1
        with:
          files: helloworld-windows-amd64-${{ github.ref_name }}
          dest: helloworld-windows-amd64-${{ github.ref_name }}.zip
      - if: matrix.os == 'windows-latest' || matrix.arch == 'arm64'
        name: create archive windows arm64
        uses: vimtor/action-zip@v1.1
        with:
          files: helloworld-windows-arm64-${{ github.ref_name }}
          dest: helloworld-windows-arm64-${{ github.ref_name }}.zip
      - if: matrix.os == 'windows-latest' || matrix.arch == 'amd64'
        name: Upload Release Asset for amd64
        id: upload-release-asset_windows_amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: ./helloworld-windows-amd64-${{ github.ref_name }}.zip
          asset_name: helloworld-windows-amd64-${{ github.ref_name }}.zip
          asset_content_type: application/zip
      - if: matrix.os == 'windows-latest' || matrix.arch == 'arm64'
        name: Upload Release Asset for arm64
        id: upload-release-asset_windows_arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: ./helloworld-windows-arm64-${{ github.ref_name }}.zip
          asset_name: helloworld-windows-arm64-${{ github.ref_name }}.zip
          asset_content_type: application/zip
      - if: matrix.os == 'windows-latest'|| matrix.arch == 'amd64'
        name: Upload Release Asset only executable for winget
        id: upload-release-asset_windows_exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: helloworld-windows-amd64-${{ github.ref_name }}
          asset_name: helloworld-amd64.exe
          asset_content_type: application/vnd.microsoft.portable-executable
